version: "3.8"

services:
  nuxt-app:
    image: floof99/project-y-nuxt-app:0.0.2
    restart: always
    ports:
      - "3000:3000"
    command: "node .output/server/index.mjs"
  web-server:
    image: floof99/project-y-web-server
    ports:
      - 8080:80
    depends_on:
      - nuxt-app


